### ISSUE TITLE
群晖docker如何启用多项服务？

### ISSUE THREAD

**Issue by zhouyisu** [cuteribs/dsm-ubuntu1604#2]
新手问题，我想同时启用ss-server和kcptun，在“环境设定”这个界面应该如何配置？
![screen shot 2017-06-22 at 23 32 12](https://user-images.githubusercontent.com/11703069/27465684-19892b58-57a3-11e7-84e9-0688695d1712.png)

**Comment by cuteribs-1** [comment]
你需要先开个ss-server容器, 然后开个kcptun容器, 在"容器间连接"里把ss-server的容器加上, 这样kcptun就能连到ss-server了

**Comment by zhouyisu** [comment]
明白了。我试一下。
